@startuml
'https://plantuml.com/class-diagram

class EarthQuake{
id
time
location
magnitude
}

class Location{
id
longitude
latitude
}

class Resource{
id
url
name
}

EarthQuake "n"  -- "1" Location
EarthQuake "n"  -- "1" Resource
@enduml