@startuml
'https://plantuml.com/class-diagram

class EarthQuake{
id
source: 数据来源 3位
where：地理信息 12位
when：时间 14位
}

class Set{
id
set：类代码 3位
count: 此set中有多少条数据 Int
}

class Affection{
id
index：序号 3位
grade: 破坏等级 1位
}

EarthQuake "1"  -- "n" Set
Set "1" -- "n" Affection
@enduml