# Generated by Django 2.2.5 on 2021-06-09 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=3)),
                ('where', models.CharField(max_length=12)),
                ('when', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(max_length=3)),
                ('count', models.IntegerField()),
                ('earthquake', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='window.Earthquake')),
            ],
        ),
        migrations.CreateModel(
            name='Affection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=3)),
                ('grade', models.CharField(max_length=1)),
                ('set', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='window.Set')),
            ],
        ),
    ]
