# Generated by Django 3.2.3 on 2021-06-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('latitude', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EarthQuake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=255)),
                ('magnitude', models.CharField(max_length=255)),
                ('location', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='window.location')),
                ('resource', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='window.resource')),
            ],
        ),
    ]
