# Generated by Django 2.2.5 on 2021-06-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('window', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earthquake',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='earthquake',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
