# Generated by Django 3.2.3 on 2021-06-09 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('window', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affection',
            name='earthquake',
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.CharField(max_length=3)),
                ('count', models.IntegerField()),
                ('earthquake', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='window.earthquake')),
            ],
        ),
        migrations.AlterField(
            model_name='affection',
            name='set',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='window.set'),
        ),
    ]
