# Generated by Django 3.2.3 on 2021-06-17 01:10

from django.db import migrations, models
import pandas as pd
import os
from window.encode import get_source_code, get_location_code, get_time_code
from window.models import Earthquake


def forwards_func(apps, schema_editor):
    # print(os.getcwd())
    df = pd.read_excel('./window/data/eqList.xls')
    for index, row in df.iterrows():
        earthquake = Earthquake.objects.create(
            source=get_source_code('公网'),
            where=get_location_code(row['参考位置']),
            when=get_time_code(row['发震时刻'])

        )
        earthquake.save()
    # db_alias = schema_editor.connection.alias
    # Earthquake = apps.get_model("window", "Earthquake")
    # Earthquake.objects.using(db_alias).bulk_create([
    #     Earthquake(source=get_source_code('公网'),
    #                where=get_location_code('参考位置'),
    #                when=get_time_code('发震时刻')
    #                )
    # ])

class Migration(migrations.Migration):

    dependencies = [
        ('window', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
